console.log(Math)
console.log(Math.abs(-4))
console.log(Math.round(4.67))
console.log(Math.ceil(4.56))
console.log(Math.floor(5.67))
console.log(Math.cbrt(64))
console.log(Math.sqrt(4))
console.log(Math.pow(2,3))

console.log(Math.log10(45))
console.log(Math.exp(342))
console.log(Math.random())
console.log(Math.max(1,2,3,45,5))
console.log(Math.min(1,2,3,45,5))

console.log('the squre root of 700 is '+Math.sqrt(700))